package vistas.form;

import Style.CustomTabbedPaneUI;
import javax.swing.*;
import java.awt.*;
import Style.Forms;
import controladores.*;
import conexion.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author dbpan
 */
public class frmEmpresa extends javax.swing.JPanel {

    private Container bgContainer;
    private BufferedImage localSelectedImage = null;
    private BufferedImage selectedImageL = null;
    Icon customIcon = new ImageIcon(getClass().getResource("/img/check_icon2.png"));

    /**
     * Creates new form FrmEmpresa
     */
    public frmEmpresa() {
        initComponents();
        bgContainer = this;
        Forms formsPanel = new Forms(bgContainer, jPTitle);
        //BottomStyle(btnActualizar);
        JTabbedPane tabbedPane = new JTabbedPane();
// Agrega pestañas al tabbedPane

// Aplica el estilo personalizado al tabbedPane
        tabbedPane.setUI(new CustomTabbedPaneUI());
        lblLogoFactura.setPreferredSize(new Dimension(154, 119));
        lblLogoFactura.setMinimumSize(new Dimension(154, 119));
        lblLogoFactura.setMaximumSize(new Dimension(154, 119));
        lblLogoFactura.setSize(new Dimension(154, 119));

        lblFotoEmpresa.setPreferredSize(new Dimension(154, 119));
        lblFotoEmpresa.setMinimumSize(new Dimension(154, 119));
        lblFotoEmpresa.setMaximumSize(new Dimension(154, 119));
        lblFotoEmpresa.setSize(new Dimension(154, 119));
        mostrarDatosEmpresa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreEmpresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRUC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDV = new javax.swing.JTextField();
        txtNombreComercialEmpresa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        txtTelefono2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFax2 = new javax.swing.JTextField();
        txtFax1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblLogoFactura = new javax.swing.JLabel();
        lblFotoEmpresa = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtProvincia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDistrito = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCorreguimiento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtUrbanizacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        txtNCasa = new javax.swing.JTextField();
        txtPiso = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        txtRNombre = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtRSegundoNombre = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtRApellidoPaterno = new javax.swing.JTextField();
        txtRApellidoMaterno = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtRCedula = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtRDV = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtRTelefono1 = new javax.swing.JTextField();
        txtRTelefono2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtRCorreo = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaOtros = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        txtGNombre = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtGCedula = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtGDV = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtGTelefono1 = new javax.swing.JTextField();
        txtGTelefono2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtGCorreo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtaActividades = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtaObervaciones = new javax.swing.JTextArea();
        jPTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1096, 849));

        bg.setForeground(new java.awt.Color(102, 102, 102));
        bg.setOpaque(false);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Nombre de la empresa");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Nombre comercial de la empresa");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        bg.add(txtNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 390, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("R.U.C. / R.U.T.");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        txtRUC.setToolTipText("Asa");
        bg.add(txtRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 170, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("D.V");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));
        bg.add(txtDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 160, -1));
        bg.add(txtNombreComercialEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 390, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Teléfonos:");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, 20));
        bg.add(txtTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 180, -1));
        bg.add(txtTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 180, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Fax:");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, -1, -1));
        bg.add(txtFax2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 160, -1));
        bg.add(txtFax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 160, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setOpaque(false);

        lblLogoFactura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoFactura.setText("Logo Factura");
        lblLogoFactura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblLogoFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogoFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoFacturaMouseClicked(evt);
            }
        });

        lblFotoEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFotoEmpresa.setText("Foto Empresa");
        lblFotoEmpresa.setToolTipText("");
        lblFotoEmpresa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblFotoEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFotoEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFotoEmpresaMouseClicked(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(102, 102, 102));
        jLabel47.setText("Logo en Factura");

        jLabel48.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(102, 102, 102));
        jLabel48.setText("Foto de la empresa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel47)
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFotoEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLogoFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel48)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblLogoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel47)
                .addGap(37, 37, 37)
                .addComponent(lblFotoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel48)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 180, 470));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel8.setText("Dirección");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(84, 187, 251));
        jSeparator1.setForeground(new java.awt.Color(84, 187, 251));
        jSeparator1.setToolTipText("");
        jSeparator1.setOpaque(true);
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 390, 3));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("País:");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));
        bg.add(txtPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 180, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Provincia:");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));
        bg.add(txtProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 190, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Distrito:");
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));
        bg.add(txtDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 390, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Correguimiento:");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));
        bg.add(txtCorreguimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 390, -1));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Urbanización:");
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));
        bg.add(txtUrbanizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 390, -1));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Calle:");
        bg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));
        bg.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 390, -1));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Casa #:");
        bg.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Piso:");
        bg.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Local");
        bg.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, -1, -1));

        txtLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalActionPerformed(evt);
            }
        });
        bg.add(txtLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 130, -1));
        bg.add(txtNCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 110, -1));
        bg.add(txtPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 110, -1));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Correo Electrónico");
        bg.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel19.setText("Representante Legal");
        bg.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(84, 187, 251));
        jSeparator2.setForeground(new java.awt.Color(84, 187, 251));
        jSeparator2.setOpaque(true);
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 400, 3));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Primer Nombre");
        bg.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));
        bg.add(txtRNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 190, -1));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Segundo Nombre");
        bg.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, -1, -1));
        bg.add(txtRSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 190, -1));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Apellido Paterno");
        bg.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Apellido Materno");
        bg.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 110, -1));
        bg.add(txtRApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 190, -1));
        bg.add(txtRApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 190, -1));

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Cédula:");
        bg.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));
        bg.add(txtRCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 190, -1));

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("D.V:");
        bg.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, -1, 20));
        bg.add(txtRDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 190, -1));

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Teléfonos:");
        bg.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));
        bg.add(txtRTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 190, -1));
        bg.add(txtRTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 190, -1));

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Correo Electrónico");
        bg.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));
        bg.add(txtRCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 400, -1));
        bg.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 390, -1));

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel28.setText("Actividades:");
        bg.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, -1, -1));

        jLabel29.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel29.setText("Observaciones:");
        bg.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, -1, -1));

        txtaOtros.setColumns(20);
        txtaOtros.setRows(5);
        jScrollPane2.setViewportView(txtaOtros);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 730, 390, 50));

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel30.setText("Gerente");
        bg.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(84, 187, 251));
        jSeparator3.setForeground(new java.awt.Color(84, 187, 251));
        jSeparator3.setOpaque(true);
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 400, 3));

        jLabel31.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Nombre:");
        bg.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, -1, -1));
        bg.add(txtGNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 400, -1));

        jLabel32.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("Cédula:");
        bg.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, -1, -1));
        bg.add(txtGCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 180, -1));

        jLabel33.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("D.V");
        bg.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, -1, -1));
        bg.add(txtGDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 560, 190, -1));

        jLabel34.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Teléfonos");
        bg.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, -1, 20));
        bg.add(txtGTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 180, -1));
        bg.add(txtGTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, 190, -1));

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Correo Electrónico");
        bg.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, -1, 20));
        bg.add(txtGCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 650, 400, -1));

        jSeparator4.setBackground(new java.awt.Color(84, 187, 251));
        jSeparator4.setForeground(new java.awt.Color(84, 187, 251));
        jSeparator4.setOpaque(true);
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 700, 400, 3));

        jLabel42.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel42.setText("Otros:");
        bg.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 710, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setOpaque(false);

        btnActualizar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizar.setFocusPainted(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnImprimir.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnImprimir.setText("Guardar");
        btnImprimir.setFocusPainted(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setFocusPainted(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnImprimir)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnActualizar.getAccessibleContext().setAccessibleParent(bg);
        btnImprimir.getAccessibleContext().setAccessibleParent(bg);

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 600, 180, 170));

        txtaActividades.setColumns(20);
        txtaActividades.setRows(5);
        jScrollPane4.setViewportView(txtaActividades);

        bg.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 390, 50));

        txtaObervaciones.setColumns(20);
        txtaObervaciones.setRows(5);
        jScrollPane5.setViewportView(txtaObervaciones);

        bg.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 730, 390, 50));

        jPTitle.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(125, 125, 125));
        jLabel1.setText("DATOS DE LA EMPRESA");

        javax.swing.GroupLayout jPTitleLayout = new javax.swing.GroupLayout(jPTitle);
        jPTitle.setLayout(jPTitleLayout);
        jPTitleLayout.setHorizontalGroup(
            jPTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(830, Short.MAX_VALUE))
        );
        jPTitleLayout.setVerticalGroup(
            jPTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bg.add(jPTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 1040, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        Connection conexion = Conexion.obtenerConexion();
        if (conexion != null) {
            Empresa obj_insertEmpresa = new Empresa();
            obj_insertEmpresa.setRuc(txtRUC.getText().trim());
            obj_insertEmpresa.setNombre(txtNombreEmpresa.getText().trim());
            obj_insertEmpresa.setNombre_comercial(txtNombreComercialEmpresa.getText().trim());
            obj_insertEmpresa.setDv(txtDV.getText().trim());
            obj_insertEmpresa.setPais(txtPais.getText().trim());
            obj_insertEmpresa.setProvincia(txtProvincia.getText().trim());
            obj_insertEmpresa.setDistrito(txtDistrito.getText().trim());
            obj_insertEmpresa.setCorregimiento(txtCorreguimiento.getText().trim());
            obj_insertEmpresa.setUrbanizacion(txtUrbanizacion.getText().trim());
            obj_insertEmpresa.setCalle(txtCalle.getText().trim());
            obj_insertEmpresa.setCasa(txtNCasa.getText().trim());
            obj_insertEmpresa.setLocal(txtLocal.getText().trim());
            obj_insertEmpresa.setPiso(txtPiso.getText().trim());
            obj_insertEmpresa.setCorreo_empresa(txtCorreo.getText().trim());
            obj_insertEmpresa.setActividades(txtaActividades.getText().trim());
            obj_insertEmpresa.setObservaciones(txtaObervaciones.getText().trim());
            obj_insertEmpresa.setTelefono1(txtTelefono1.getText().trim());
            obj_insertEmpresa.setTelefono2(txtTelefono2.getText().trim());
            obj_insertEmpresa.setFax1(txtFax1.getText().trim());
            obj_insertEmpresa.setFax2(txtFax2.getText().trim());
            obj_insertEmpresa.setPrimer_nombre_representante(txtRNombre.getText().trim());
            obj_insertEmpresa.setSegundo_nombre_representante(txtRSegundoNombre.getText().trim());
            obj_insertEmpresa.setApellido_paterno(txtRApellidoPaterno.getText().trim());
            obj_insertEmpresa.setApellido_materno(txtRApellidoMaterno.getText().trim());
            obj_insertEmpresa.setCedula(txtRCedula.getText().trim());
            obj_insertEmpresa.setDv_representante(txtRDV.getText().trim());
            obj_insertEmpresa.setTelefono1_representante(txtRTelefono1.getText().trim());
            obj_insertEmpresa.setTelefono2_representante(txtRTelefono2.getText().trim());
            obj_insertEmpresa.setCorreo_representante(txtRCorreo.getText().trim());
            obj_insertEmpresa.setNombre_gerente(txtGNombre.getText().trim());
            obj_insertEmpresa.setCedula_gerente(txtGCedula.getText().trim());
            obj_insertEmpresa.setDv_gerente(txtGDV.getText().trim());
            obj_insertEmpresa.setTelefono_gerente1(txtGTelefono1.getText().trim());
            obj_insertEmpresa.setTelefono_gerente2(txtGTelefono2.getText().trim());
            obj_insertEmpresa.setCorreo_gerente(txtGCorreo.getText().trim());
            obj_insertEmpresa.setOtros(txtaOtros.getText().trim());
            //obj_insertEmpresa.setFecha_actualizacion(new Date());

            // Insertar la imagen en la base de datos
            if (selectedImageL != null) {
                try {
                    ByteArrayOutputStream baos = new ByteArrayOutputStream();
                    ImageIO.write(selectedImageL, "jpg", baos);
                    byte[] imageBytes = baos.toByteArray();
                    obj_insertEmpresa.setLogo_factura(imageBytes);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }

            if (localSelectedImage != null) {
                try {
                    ByteArrayOutputStream baos = new ByteArrayOutputStream();
                    ImageIO.write(localSelectedImage, "jpg", baos);
                    byte[] imageBytes = baos.toByteArray();
                    obj_insertEmpresa.setLogo_empresa(imageBytes);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                System.out.println("selectedImageL es nulo. Asegúrate de que la imagen esté cargada correctamente.");
            }

            //se ingresa informacion 
            if (obj_insertEmpresa.updateEmpresa(conexion)) {
                // Show a success message using JOptionPane
                JOptionPane.showMessageDialog(null, "Los datos se han guardado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE, customIcon);
            } else {
                // Show an error message using JOptionPane
                JOptionPane.showMessageDialog(this, "Error al insertar los datos", "Error", JOptionPane.ERROR_MESSAGE);
            }

            Conexion.cerrarConexion(conexion);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalActionPerformed

    public void mostrarDatosEmpresa() {
        // Se obtiene una conexión a la base de datos
        Connection conexion = Conexion.obtenerConexion();

        // Se crea un objeto de la clase "Empresa" para manejar la información de la empresa
        Empresa empresa = new Empresa();

        // Verifica si la conexión a la base de datos es exitosa
        if (conexion != null) {
            empresa.selectEmpresa(conexion);
            // Se cierra la conexión a la base de datos
            Conexion.cerrarConexion(conexion);
        }

        // Actualiza los campos de texto y áreas de texto en el formulario con la información de la empresa
        txtRUC.setText(empresa.getRuc());
        txtNombreEmpresa.setText(empresa.getNombre());
        txtNombreComercialEmpresa.setText(empresa.getNombre_comercial());
        txtDV.setText(empresa.getDv());
        txtPais.setText(empresa.getPais());
        txtProvincia.setText(empresa.getProvincia());
        txtDistrito.setText(empresa.getDistrito());
        txtCorreguimiento.setText(empresa.getCorregimiento());
        txtUrbanizacion.setText(empresa.getUrbanizacion());
        txtCalle.setText(empresa.getCalle());
        txtNCasa.setText(empresa.getCasa());
        txtLocal.setText(empresa.getLocal());
        txtPiso.setText(empresa.getPiso());
        txtCorreo.setText(empresa.getCorreo_empresa());
        txtaActividades.setText(empresa.getActividades());
        txtaObervaciones.setText(empresa.getObservaciones());
        txtTelefono1.setText(empresa.getTelefono1());
        txtTelefono2.setText(empresa.getTelefono2());
        txtFax1.setText(empresa.getFax1());
        txtFax2.setText(empresa.getFax2());
        txtRNombre.setText(empresa.getPrimer_nombre_representante());
        txtRSegundoNombre.setText(empresa.getSegundo_nombre_representante());
        txtRApellidoPaterno.setText(empresa.getApellido_paterno());
        txtRApellidoMaterno.setText(empresa.getApellido_materno());
        txtRCedula.setText(empresa.getCedula());
        txtRDV.setText(empresa.getDv_representante());
        txtRTelefono1.setText(empresa.getTelefono1_representante());
        txtRTelefono2.setText(empresa.getTelefono2_representante());
        txtRCorreo.setText(empresa.getCorreo_representante());
        txtGNombre.setText(empresa.getNombre_gerente());
        txtGCedula.setText(empresa.getCedula_gerente());
        txtGDV.setText(empresa.getDv_gerente());
        txtGTelefono1.setText(empresa.getTelefono_gerente1());
        txtGTelefono2.setText(empresa.getTelefono_gerente2());
        txtGCorreo.setText(empresa.getCorreo_gerente());
        txtaOtros.setText(empresa.getOtros());

        byte[] logoFacturaBytes = empresa.getLogo_factura();
        if (logoFacturaBytes != null) {
            try {
                // Convertir el array de bytes a una ImageIcon
                ImageIcon imagenFactura = new ImageIcon(logoFacturaBytes);

                // Escalar la imagen al tamaño deseado
                int width = 154;
                int height = 119;
                Image imagenEscalada = imagenFactura.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);

                // Crear un nuevo ImageIcon con la imagen escalada
                ImageIcon imagenEscaladaIcon = new ImageIcon(imagenEscalada);

                // Establecer el nuevo ImageIcon en el JLabel
                lblLogoFactura.setIcon(imagenEscaladaIcon);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        // Manejo de las imágenes de la empresa
        byte[] logoEmpresaBytes = empresa.getLogo_empresa();
        if (logoEmpresaBytes != null) {
            try {
                // Convertir el array de bytes a una ImageIcon
                ImageIcon fotoEmpresa = new ImageIcon(logoEmpresaBytes);

                // Escalar la imagen al tamaño deseado
                int widthEmpresa = 154;  // Tamaño deseado para el ancho
                int heightEmpresa = 119; // Tamaño deseado para el alto
                Image fotoEscalada = fotoEmpresa.getImage().getScaledInstance(widthEmpresa, heightEmpresa, Image.SCALE_SMOOTH);

                // Crear un nuevo ImageIcon con la imagen escalada
                ImageIcon fotoEscaladaIcon = new ImageIcon(fotoEscalada);

                // Establecer el nuevo ImageIcon en el JLabel
                lblFotoEmpresa.setIcon(fotoEscaladaIcon);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }


    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        Connection conexion = Conexion.obtenerConexion();
        if (conexion != null) {
            Empresa obj_insertEmpresa = new Empresa();
            obj_insertEmpresa.setRuc(txtRUC.getText().trim());
            obj_insertEmpresa.setNombre(txtNombreEmpresa.getText().trim());
            obj_insertEmpresa.setNombre_comercial(txtNombreComercialEmpresa.getText().trim());
            obj_insertEmpresa.setDv(txtDV.getText().trim());
            obj_insertEmpresa.setPais(txtPais.getText().trim());
            obj_insertEmpresa.setProvincia(txtProvincia.getText().trim());
            obj_insertEmpresa.setDistrito(txtDistrito.getText().trim());
            obj_insertEmpresa.setCorregimiento(txtCorreguimiento.getText().trim());
            obj_insertEmpresa.setUrbanizacion(txtUrbanizacion.getText().trim());
            obj_insertEmpresa.setCalle(txtCalle.getText().trim());
            obj_insertEmpresa.setCasa(txtNCasa.getText().trim());
            obj_insertEmpresa.setLocal(txtLocal.getText().trim());
            obj_insertEmpresa.setPiso(txtPiso.getText().trim());
            obj_insertEmpresa.setCorreo_empresa(txtCorreo.getText().trim());
            obj_insertEmpresa.setActividades(txtaActividades.getText().trim());
            obj_insertEmpresa.setObservaciones(txtaObervaciones.getText().trim());
            obj_insertEmpresa.setTelefono1(txtTelefono1.getText().trim());
            obj_insertEmpresa.setTelefono2(txtTelefono2.getText().trim());
            obj_insertEmpresa.setFax1(txtFax1.getText().trim());
            obj_insertEmpresa.setFax2(txtFax2.getText().trim());
            obj_insertEmpresa.setPrimer_nombre_representante(txtRNombre.getText().trim());
            obj_insertEmpresa.setSegundo_nombre_representante(txtRSegundoNombre.getText().trim());
            obj_insertEmpresa.setApellido_paterno(txtRApellidoPaterno.getText().trim());
            obj_insertEmpresa.setApellido_materno(txtRApellidoMaterno.getText().trim());
            obj_insertEmpresa.setCedula(txtRCedula.getText().trim());
            obj_insertEmpresa.setDv_representante(txtRDV.getText().trim());
            obj_insertEmpresa.setTelefono1_representante(txtRTelefono1.getText().trim());
            obj_insertEmpresa.setTelefono2_representante(txtRTelefono2.getText().trim());
            obj_insertEmpresa.setCorreo_representante(txtRCorreo.getText().trim());
            obj_insertEmpresa.setNombre_gerente(txtGNombre.getText().trim());
            obj_insertEmpresa.setCedula_gerente(txtGCedula.getText().trim());
            obj_insertEmpresa.setDv_gerente(txtGDV.getText().trim());
            obj_insertEmpresa.setTelefono_gerente1(txtGTelefono1.getText().trim());
            obj_insertEmpresa.setTelefono_gerente2(txtGTelefono2.getText().trim());
            obj_insertEmpresa.setCorreo_gerente(txtGCorreo.getText().trim());
            obj_insertEmpresa.setOtros(txtaOtros.getText().trim());
            //obj_insertEmpresa.setFecha_actualizacion(new Date());

            // Insertar la imagen en la base de datos
            if (selectedImageL != null) {
                try {
                    ByteArrayOutputStream baos = new ByteArrayOutputStream();
                    ImageIO.write(selectedImageL, "jpg", baos);
                    byte[] imageBytes = baos.toByteArray();
                    obj_insertEmpresa.setLogo_factura(imageBytes);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }

            if (localSelectedImage != null) {
                try {
                    ByteArrayOutputStream baos = new ByteArrayOutputStream();
                    ImageIO.write(localSelectedImage, "jpg", baos);
                    byte[] imageBytes = baos.toByteArray();
                    obj_insertEmpresa.setLogo_empresa(imageBytes);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                System.out.println("selectedImageL es nulo. Asegúrate de que la imagen esté cargada correctamente.");
            }

            //se ingresa informacion 
            if (obj_insertEmpresa.insertEmpresa(conexion)) {
                // Show a success message using JOptionPane
                JOptionPane.showMessageDialog(null, "Los datos se han guardado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE, customIcon);
            } else {
                // Show an error message using JOptionPane
                JOptionPane.showMessageDialog(this, "Error al insertar los datos", "Error", JOptionPane.ERROR_MESSAGE);
            }

            Conexion.cerrarConexion(conexion);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void lblLogoFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoFacturaMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Archivos de imagen", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(imageFilter);

        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            try {
                selectedImageL = ImageIO.read(selectedFile);

                // Escalar la imagen para que se ajuste al tamaño del JLabel
                int width = 154;
                int height = 119;
                Image scaledImage = selectedImageL.getScaledInstance(width, height, Image.SCALE_SMOOTH);

                // Mostrar la imagen en el JLabel
                ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
                lblLogoFactura.setIcon(scaledImageIcon);

                // No necesitas convertir la imagen a byte[] aquí, puedes hacerlo más tarde si es necesario
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_lblLogoFacturaMouseClicked

    private void lblFotoEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoEmpresaMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Archivos de imagen", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(imageFilter);

        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            try {
                localSelectedImage = ImageIO.read(selectedFile); // Cambia el nombre de la variable local

                // Escalar la imagen para que se ajuste al tamaño del JLabel
                int width = 154;
                int height = 119;
                Image scaledImage = localSelectedImage.getScaledInstance(width, height, Image.SCALE_SMOOTH);

                // Mostrar la imagen en el JLabel
                ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
                lblFotoEmpresa.setIcon(scaledImageIcon);

                // Si deseas convertir la imagen a byte[] para guardarla en la base de datos, puedes hacerlo aquí
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_lblFotoEmpresaMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        LimpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void LimpiarCampos(){
        txtRUC.setText(" ");
        txtNombreEmpresa.setText(" ");
        txtNombreComercialEmpresa.setText(" ");
        txtDV.setText(" ");
        txtPais.setText(" ");
        txtProvincia.setText(" ");
        txtDistrito.setText(" ");
        txtCorreguimiento.setText(" ");
        txtUrbanizacion.setText(" ");
        txtCalle.setText(" ");
        txtNCasa.setText(" ");
        txtLocal.setText(" ");
        txtPiso.setText(" ");
        txtCorreo.setText(" ");
        txtaActividades.setText(" ");
        txtaObervaciones.setText(" ");
        txtTelefono1.setText(" ");
        txtTelefono2.setText(" ");
        txtFax1.setText(" ");
        txtFax2.setText(" ");
        txtRNombre.setText(" ");
        txtRSegundoNombre.setText(" ");
        txtRApellidoPaterno.setText(" ");
        txtRApellidoMaterno.setText(" ");
        txtRCedula.setText(" ");
        txtRDV.setText(" ");
        txtRTelefono1.setText(" ");
        txtRTelefono2.setText(" ");
        txtRCorreo.setText(" ");
        txtGNombre.setText(" ");
        txtGCedula.setText(" ");
        txtGDV.setText(" ");
        txtGTelefono1.setText(" ");
        txtGTelefono2.setText(" ");
        txtGCorreo.setText(" ");
        txtaOtros.setText(" ");  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPTitle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblFotoEmpresa;
    private javax.swing.JLabel lblLogoFactura;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCorreguimiento;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDV;
    private javax.swing.JTextField txtDistrito;
    private javax.swing.JTextField txtFax1;
    private javax.swing.JTextField txtFax2;
    private javax.swing.JTextField txtGCedula;
    private javax.swing.JTextField txtGCorreo;
    private javax.swing.JTextField txtGDV;
    private javax.swing.JTextField txtGNombre;
    private javax.swing.JTextField txtGTelefono1;
    private javax.swing.JTextField txtGTelefono2;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtNCasa;
    private javax.swing.JTextField txtNombreComercialEmpresa;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPiso;
    private javax.swing.JTextField txtProvincia;
    private javax.swing.JTextField txtRApellidoMaterno;
    private javax.swing.JTextField txtRApellidoPaterno;
    private javax.swing.JTextField txtRCedula;
    private javax.swing.JTextField txtRCorreo;
    private javax.swing.JTextField txtRDV;
    private javax.swing.JTextField txtRNombre;
    private javax.swing.JTextField txtRSegundoNombre;
    private javax.swing.JTextField txtRTelefono1;
    private javax.swing.JTextField txtRTelefono2;
    private javax.swing.JTextField txtRUC;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextField txtTelefono2;
    private javax.swing.JTextField txtUrbanizacion;
    private javax.swing.JTextArea txtaActividades;
    private javax.swing.JTextArea txtaObervaciones;
    private javax.swing.JTextArea txtaOtros;
    // End of variables declaration//GEN-END:variables
}
