/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package vistas.form;

/**
 *
 * @author admin
 */
public class frmHistorialDoc extends javax.swing.JFrame {

    /** Creates new form frmHistorialDoc */
    public frmHistorialDoc() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        lblIDFactura = new javax.swing.JLabel();
        lblnombrecliente1 = new javax.swing.JLabel();
        jlabel40 = new javax.swing.JLabel();
        lblCedula1 = new javax.swing.JLabel();
        jlabel42 = new javax.swing.JLabel();
        jlabel43 = new javax.swing.JLabel();
        lblTipoDoc = new javax.swing.JLabel();
        lbltelefono2 = new javax.swing.JLabel();
        lbltelefono1 = new javax.swing.JLabel();
        jlabel41 = new javax.swing.JLabel();
        jlabel45 = new javax.swing.JLabel();
        lblestado = new javax.swing.JLabel();
        jlabel46 = new javax.swing.JLabel();
        lblreferencia = new javax.swing.JLabel();
        jlabel55 = new javax.swing.JLabel();
        jlabel60 = new javax.swing.JLabel();
        lblFormaPago1 = new javax.swing.JLabel();
        lblFormaPago3 = new javax.swing.JLabel();
        jlabel57 = new javax.swing.JLabel();
        lblFormaPago2 = new javax.swing.JLabel();
        jlabel56 = new javax.swing.JLabel();
        lblMontoPago2 = new javax.swing.JLabel();
        jlabel58 = new javax.swing.JLabel();
        lblFormaPago4 = new javax.swing.JLabel();
        lblMontoPago3 = new javax.swing.JLabel();
        lblMontoPago1 = new javax.swing.JLabel();
        lblMontoPago4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtfDireccion = new javax.swing.JTextArea();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDocumentos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jlabel44 = new javax.swing.JLabel();
        jlabel47 = new javax.swing.JLabel();
        jlabel48 = new javax.swing.JLabel();
        jlabel49 = new javax.swing.JLabel();
        jlabel50 = new javax.swing.JLabel();
        jlabel51 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblMontoTotal = new javax.swing.JLabel();
        lblDescGenTotal = new javax.swing.JLabel();
        lblDescLineaTotal = new javax.swing.JLabel();
        lblImpuestoTotal = new javax.swing.JLabel();
        lblSubTotal1 = new javax.swing.JLabel();
        jlabel53 = new javax.swing.JLabel();
        lblDiferencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(388, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 0, 0));
        jLabel39.setText("Factura ");

        lblIDFactura.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblIDFactura.setForeground(new java.awt.Color(51, 51, 51));
        lblIDFactura.setText("####");

        lblnombrecliente1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblnombrecliente1.setText("NombreCliente");

        jlabel40.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel40.setText("Nombre :");

        lblCedula1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblCedula1.setText("Cedula");

        jlabel42.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel42.setText("Cedula :");

        jlabel43.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel43.setText("Telefono :");

        lblTipoDoc.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblTipoDoc.setForeground(new java.awt.Color(102, 102, 102));
        lblTipoDoc.setText("TipoDoc");

        lbltelefono2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lbltelefono2.setText("Telefono2");

        lbltelefono1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lbltelefono1.setText("Telefono1");

        jlabel41.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel41.setText("Direccion :");

        jlabel45.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel45.setText("Referencia :");

        lblestado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblestado.setText("Estado");

        jlabel46.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel46.setText("Estado :");

        lblreferencia.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblreferencia.setText("Estado Doc");

        jlabel55.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel55.setText("Forma de Pago:");

        jlabel60.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel60.setText("Monto Pago");

        lblFormaPago1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblFormaPago1.setText("FormaPago1");

        lblFormaPago3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblFormaPago3.setText("FormaPago3");

        jlabel57.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel57.setText("Forma de Pago:");

        lblFormaPago2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblFormaPago2.setText("FormaPago2");

        jlabel56.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel56.setText("Forma de Pago:");

        lblMontoPago2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblMontoPago2.setText("MontoPago2");

        jlabel58.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel58.setText("Forma de Pago:");

        lblFormaPago4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblFormaPago4.setText("FormaPago4");

        lblMontoPago3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblMontoPago3.setText("MontoPago3");

        lblMontoPago1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblMontoPago1.setText("MontoPago1");

        lblMontoPago4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblMontoPago4.setText("MontoPago4");

        txtfDireccion.setEditable(false);
        txtfDireccion.setColumns(20);
        txtfDireccion.setLineWrap(true);
        txtfDireccion.setRows(5);
        jScrollPane2.setViewportView(txtfDireccion);

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel45.setText("Fecha/ Hora Impresión :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabel40)
                            .addComponent(jlabel42))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblnombrecliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel45)
                                    .addComponent(jlabel41)
                                    .addComponent(jlabel46)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIDFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTipoDoc)
                        .addGap(143, 143, 143)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlabel43)
                        .addGap(18, 18, 18)
                        .addComponent(lbltelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lbltelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblestado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFormaPago1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlabel58, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFormaPago3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlabel57, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFormaPago4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFormaPago2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMontoPago2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMontoPago3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMontoPago1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMontoPago4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel60)
                            .addComponent(lblTipoDoc)
                            .addComponent(jLabel45)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlabel55)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel39)
                                    .addComponent(lblIDFactura))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlabel40)
                                    .addComponent(lblnombrecliente1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlabel41)
                                    .addComponent(jlabel42)
                                    .addComponent(lblCedula1))
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblFormaPago1)
                                .addGap(18, 18, 18)
                                .addComponent(jlabel56)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFormaPago2)
                                .addGap(18, 18, 18)))
                        .addComponent(jlabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFormaPago3)
                            .addComponent(jlabel43)
                            .addComponent(lbltelefono1))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jlabel57)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFormaPago4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbltelefono2)))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblMontoPago1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblestado)
                                    .addComponent(jlabel46))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlabel45)
                                    .addComponent(lblreferencia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lblMontoPago2)
                                .addGap(41, 41, 41)
                                .addComponent(lblMontoPago3)
                                .addGap(48, 48, 48)
                                .addComponent(lblMontoPago4)
                                .addContainerGap(32, Short.MAX_VALUE))))))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane1ComponentAdded(evt);
            }
        });

        TableDocumentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Articulo/ Servicio", "¿Servicio?", "Descripción", "Magnitud", "Cantidad", "Precio", "Desc. Linea", "Desc. General", "Base", "I.T.B.M.S", "Importe I.T.B.M.S", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableDocumentos.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(TableDocumentos);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlabel44.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel44.setText("Desc. General Total :");

        jlabel47.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel47.setText("Impuesto Total :");

        jlabel48.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel48.setText("Desc.Línea Total :");

        jlabel49.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel49.setText("Monto Total :");

        jlabel50.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel50.setText("Subtotal :");

        jlabel51.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel51.setText("Diferencia :");

        lblTotal.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblTotal.setText("Total");

        lblMontoTotal.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblMontoTotal.setText("Montotal");

        lblDescGenTotal.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblDescGenTotal.setText("DescGenTotal");

        lblDescLineaTotal.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblDescLineaTotal.setText("DescLineaTotal");

        lblImpuestoTotal.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblImpuestoTotal.setText("ImpuestoTotal");

        lblSubTotal1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblSubTotal1.setText("SubTotal");

        jlabel53.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jlabel53.setText("Total :");

        lblDiferencia.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblDiferencia.setText("Diferencia");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel49)
                    .addComponent(lblMontoTotal))
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescLineaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescGenTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel50)
                    .addComponent(jlabel53))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSubTotal1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel47)
                    .addComponent(jlabel51))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImpuestoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel47)
                            .addComponent(jlabel49)
                            .addComponent(jlabel48)
                            .addComponent(lblDescLineaTotal)
                            .addComponent(lblImpuestoTotal)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel50)
                            .addComponent(lblSubTotal1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlabel44)
                        .addComponent(lblDescGenTotal)
                        .addComponent(jlabel53)
                        .addComponent(lblTotal)
                        .addComponent(jlabel51))
                    .addComponent(lblMontoTotal)
                    .addComponent(lblDiferencia))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1065, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1ComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHistorialDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHistorialDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHistorialDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHistorialDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHistorialDoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDocumentos;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabel40;
    private javax.swing.JLabel jlabel41;
    private javax.swing.JLabel jlabel42;
    private javax.swing.JLabel jlabel43;
    private javax.swing.JLabel jlabel44;
    private javax.swing.JLabel jlabel45;
    private javax.swing.JLabel jlabel46;
    private javax.swing.JLabel jlabel47;
    private javax.swing.JLabel jlabel48;
    private javax.swing.JLabel jlabel49;
    private javax.swing.JLabel jlabel50;
    private javax.swing.JLabel jlabel51;
    private javax.swing.JLabel jlabel53;
    private javax.swing.JLabel jlabel55;
    private javax.swing.JLabel jlabel56;
    private javax.swing.JLabel jlabel57;
    private javax.swing.JLabel jlabel58;
    private javax.swing.JLabel jlabel60;
    private javax.swing.JLabel lblCedula1;
    private javax.swing.JLabel lblDescGenTotal;
    private javax.swing.JLabel lblDescLineaTotal;
    private javax.swing.JLabel lblDiferencia;
    private javax.swing.JLabel lblFormaPago1;
    private javax.swing.JLabel lblFormaPago2;
    private javax.swing.JLabel lblFormaPago3;
    private javax.swing.JLabel lblFormaPago4;
    private javax.swing.JLabel lblIDFactura;
    private javax.swing.JLabel lblImpuestoTotal;
    private javax.swing.JLabel lblMontoPago1;
    private javax.swing.JLabel lblMontoPago2;
    private javax.swing.JLabel lblMontoPago3;
    private javax.swing.JLabel lblMontoPago4;
    private javax.swing.JLabel lblMontoTotal;
    private javax.swing.JLabel lblSubTotal1;
    private javax.swing.JLabel lblTipoDoc;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblnombrecliente1;
    private javax.swing.JLabel lblreferencia;
    private javax.swing.JLabel lbltelefono1;
    private javax.swing.JLabel lbltelefono2;
    private javax.swing.JTextArea txtfDireccion;
    // End of variables declaration//GEN-END:variables

}
